[package]
name = "fast-conventional"
version = "1.0.8"
edition = "2021"
categories = ["development-tools","command-line-utilities"]
keywords = ["git", "commit message"]
description = "Make conventional commits, faster, and consistently name scopes"
repository = "https://github.com/PurpleBooth/fast-conventional"
license = "CC0-1.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]

[dependencies]
serde = { version = "1.0.134", features = ["derive"] }
serde_yaml = "0.8.23"
inquire = { version = "0.2.1", features = [ "editor"] }
miette = { version = "3.3.0", features = ["fancy"] }
clap_complete = "3.0.4"
clap = { version = "3.0.12", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }
mit-commit = "3.0.0"
