[package]
name = "fast-conventional"
version = "2.3.4"
edition = "2021"
categories = ["development-tools","command-line-utilities"]
keywords = ["git", "commit_message"]
description = "Make conventional commits, faster, and consistently name scopes"
repository = "https://github.com/PurpleBooth/fast-conventional"
license = "CC0-1.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]

[dependencies]
nom = "7.1.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_yaml = "0.9.14"
inquire = { version = "0.5.2", features = [ "editor"] }
miette = { version = "5.4.1", features = ["fancy"] }
clap_complete = "4.0.7"
clap = { version = "4.0.18", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
mit-commit = "3.1.4"
thiserror = "1.0.37"
git2 = "0.15.0"
[dev-dependencies]
tempfile = "3.3.0"
