[package]
name = "fast-conventional"
version = "2.3.0"
edition = "2021"
categories = ["development-tools","command-line-utilities"]
keywords = ["git", "commit_message"]
description = "Make conventional commits, faster, and consistently name scopes"
repository = "https://github.com/PurpleBooth/fast-conventional"
license = "CC0-1.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]

[dependencies]
nom = "7.1.1"
serde = { version = "1.0.144", features = ["derive"] }
serde_yaml = "0.8.24"
inquire = { version = "0.2.1", features = [ "editor"] }
miette = { version = "4.7.1", features = ["fancy"] }
clap_complete = "3.1.4"
clap = { version = "3.1.18", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }
mit-commit = "3.1.1"
thiserror = "1.0.31"
git2 = "0.14"
[dev-dependencies]
tempfile = "3.3.0"
