[package]
name = "fast-conventional"
version = "1.0.13"
edition = "2021"
categories = ["development-tools","command-line-utilities"]
keywords = ["git", "commit_message"]
description = "Make conventional commits, faster, and consistently name scopes"
repository = "https://github.com/PurpleBooth/fast-conventional"
license = "CC0-1.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
inquire = { version = "0.2.1", features = [ "editor"] }
miette = { version = "4.1.0", features = ["fancy"] }
clap_complete = "3.1.0"
clap = { version = "3.1.1", features = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode" ] }
mit-commit = "3.0.1"
thiserror = "1.0.30"
[dev-dependencies]
tempfile = "3.3.0"
