[package]
name = "fast-conventional"
version = "0.1.4"
edition = "2021"
categories = ["development-tools","command-line-utilities"]
keywords = ["git", "commit message"]
description = "A fast way to fill in conventional commit messages"
repository = "https://github.com/PurpleBooth/fast-conventional"
license = "CC0-1.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
inquire = { version = "0.2.1", features = [ "editor"] }
miette = { version = "3.2.0", features = ["fancy"] }
clap_derive = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
clap = "3.0.0-beta.5"
mit-commit = "3.0.0"
