[package]
name = "fast-conventional"
version = "2.3.4"
edition = "2021"
categories = ["development-tools","command-line-utilities"]
keywords = ["git", "commit_message"]
description = "Make conventional commits, faster, and consistently name scopes"
repository = "https://github.com/PurpleBooth/fast-conventional"
license = "CC0-1.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]

[dependencies]
nom = "7.1.3"
serde = { version = "1.0.196", features = ["derive"] }
serde_yaml = "0.9.32"
inquire = { version = "0.6.2", features = [ "editor"] }
miette = { version = "7.0.0", features = ["fancy"] }
clap_complete = "4.5.0"
clap = { version = "4.5.0", features = ["derive", "cargo", "wrap_help", "env", "unicode" ] }
mit-commit = "3.1.5"
thiserror = "1.0.57"
git2 = "0.18.2"
[dev-dependencies]
tempfile = "3.10.0"
